name: Bug report
description: Report a bug or documentation issue
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Links or references
