name: Documentation change
description: Request a documentation update
title: "[Docs]: "
labels: [documentation]
body:
  - type: textarea
    id: change
    attributes:
      label: Requested change
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
