name: Service request
description: Request a Cloud Security Service update
title: "[Service]: "
labels: [service]
body:
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Describe the requested service change
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
